// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/magnet2torrent.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Magnet2Torrent_Magnet2Torrent_FullMethodName = "/Magnet2Torrent/Magnet2Torrent"
)

// Magnet2TorrentClient is the client API for Magnet2Torrent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Magnet2TorrentClient interface {
	// Converts magnet uri to torrent file
	Magnet2Torrent(ctx context.Context, in *Magnet2TorrentRequest, opts ...grpc.CallOption) (*Magnet2TorrentReply, error)
}

type magnet2TorrentClient struct {
	cc grpc.ClientConnInterface
}

func NewMagnet2TorrentClient(cc grpc.ClientConnInterface) Magnet2TorrentClient {
	return &magnet2TorrentClient{cc}
}

func (c *magnet2TorrentClient) Magnet2Torrent(ctx context.Context, in *Magnet2TorrentRequest, opts ...grpc.CallOption) (*Magnet2TorrentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Magnet2TorrentReply)
	err := c.cc.Invoke(ctx, Magnet2Torrent_Magnet2Torrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Magnet2TorrentServer is the server API for Magnet2Torrent service.
// All implementations must embed UnimplementedMagnet2TorrentServer
// for forward compatibility.
type Magnet2TorrentServer interface {
	// Converts magnet uri to torrent file
	Magnet2Torrent(context.Context, *Magnet2TorrentRequest) (*Magnet2TorrentReply, error)
	mustEmbedUnimplementedMagnet2TorrentServer()
}

// UnimplementedMagnet2TorrentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMagnet2TorrentServer struct{}

func (UnimplementedMagnet2TorrentServer) Magnet2Torrent(context.Context, *Magnet2TorrentRequest) (*Magnet2TorrentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Magnet2Torrent not implemented")
}
func (UnimplementedMagnet2TorrentServer) mustEmbedUnimplementedMagnet2TorrentServer() {}
func (UnimplementedMagnet2TorrentServer) testEmbeddedByValue()                        {}

// UnsafeMagnet2TorrentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Magnet2TorrentServer will
// result in compilation errors.
type UnsafeMagnet2TorrentServer interface {
	mustEmbedUnimplementedMagnet2TorrentServer()
}

func RegisterMagnet2TorrentServer(s grpc.ServiceRegistrar, srv Magnet2TorrentServer) {
	// If the following call pancis, it indicates UnimplementedMagnet2TorrentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Magnet2Torrent_ServiceDesc, srv)
}

func _Magnet2Torrent_Magnet2Torrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Magnet2TorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Magnet2TorrentServer).Magnet2Torrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Magnet2Torrent_Magnet2Torrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Magnet2TorrentServer).Magnet2Torrent(ctx, req.(*Magnet2TorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Magnet2Torrent_ServiceDesc is the grpc.ServiceDesc for Magnet2Torrent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Magnet2Torrent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Magnet2Torrent",
	HandlerType: (*Magnet2TorrentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Magnet2Torrent",
			Handler:    _Magnet2Torrent_Magnet2Torrent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/magnet2torrent.proto",
}
