// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: proto/magnet2torrent.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the magnet url
type Magnet2TorrentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Magnet string `protobuf:"bytes,1,opt,name=magnet,proto3" json:"magnet,omitempty"`
}

func (x *Magnet2TorrentRequest) Reset() {
	*x = Magnet2TorrentRequest{}
	mi := &file_proto_magnet2torrent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Magnet2TorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Magnet2TorrentRequest) ProtoMessage() {}

func (x *Magnet2TorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_magnet2torrent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Magnet2TorrentRequest.ProtoReflect.Descriptor instead.
func (*Magnet2TorrentRequest) Descriptor() ([]byte, []int) {
	return file_proto_magnet2torrent_proto_rawDescGZIP(), []int{0}
}

func (x *Magnet2TorrentRequest) GetMagnet() string {
	if x != nil {
		return x.Magnet
	}
	return ""
}

// The response message containing the torrent
type Magnet2TorrentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Torrent []byte `protobuf:"bytes,1,opt,name=torrent,proto3" json:"torrent,omitempty"`
}

func (x *Magnet2TorrentReply) Reset() {
	*x = Magnet2TorrentReply{}
	mi := &file_proto_magnet2torrent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Magnet2TorrentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Magnet2TorrentReply) ProtoMessage() {}

func (x *Magnet2TorrentReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_magnet2torrent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Magnet2TorrentReply.ProtoReflect.Descriptor instead.
func (*Magnet2TorrentReply) Descriptor() ([]byte, []int) {
	return file_proto_magnet2torrent_proto_rawDescGZIP(), []int{1}
}

func (x *Magnet2TorrentReply) GetTorrent() []byte {
	if x != nil {
		return x.Torrent
	}
	return nil
}

var File_proto_magnet2torrent_proto protoreflect.FileDescriptor

var file_proto_magnet2torrent_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x32, 0x74,
	0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x15,
	0x4d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x32, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x22, 0x2f, 0x0a,
	0x13, 0x4d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x32, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x32, 0x52,
	0x0a, 0x0e, 0x4d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x32, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x12, 0x40, 0x0a, 0x0e, 0x4d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x32, 0x54, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x2e, 0x4d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x32, 0x54, 0x6f, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4d, 0x61, 0x67,
	0x6e, 0x65, 0x74, 0x32, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_magnet2torrent_proto_rawDescOnce sync.Once
	file_proto_magnet2torrent_proto_rawDescData = file_proto_magnet2torrent_proto_rawDesc
)

func file_proto_magnet2torrent_proto_rawDescGZIP() []byte {
	file_proto_magnet2torrent_proto_rawDescOnce.Do(func() {
		file_proto_magnet2torrent_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_magnet2torrent_proto_rawDescData)
	})
	return file_proto_magnet2torrent_proto_rawDescData
}

var file_proto_magnet2torrent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_magnet2torrent_proto_goTypes = []any{
	(*Magnet2TorrentRequest)(nil), // 0: Magnet2TorrentRequest
	(*Magnet2TorrentReply)(nil),   // 1: Magnet2TorrentReply
}
var file_proto_magnet2torrent_proto_depIdxs = []int32{
	0, // 0: Magnet2Torrent.Magnet2Torrent:input_type -> Magnet2TorrentRequest
	1, // 1: Magnet2Torrent.Magnet2Torrent:output_type -> Magnet2TorrentReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_magnet2torrent_proto_init() }
func file_proto_magnet2torrent_proto_init() {
	if File_proto_magnet2torrent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_magnet2torrent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_magnet2torrent_proto_goTypes,
		DependencyIndexes: file_proto_magnet2torrent_proto_depIdxs,
		MessageInfos:      file_proto_magnet2torrent_proto_msgTypes,
	}.Build()
	File_proto_magnet2torrent_proto = out.File
	file_proto_magnet2torrent_proto_rawDesc = nil
	file_proto_magnet2torrent_proto_goTypes = nil
	file_proto_magnet2torrent_proto_depIdxs = nil
}
